export const dashboardHtml = `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>MTTL-W01 Matter Bridge</title>
  <style>
    :root{color-scheme:dark;--bg:#07111f;--panel:#101d2d;--line:#24364b;--text:#edf5ff;--muted:#8fa4ba;--mint:#47e6b1;--blue:#55a7ff;--red:#ff7184}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--bg);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Noto Sans KR",sans-serif;color:var(--text)}
    main{width:min(1160px,calc(100% - 32px));margin:auto;padding:34px 0 56px}header{display:flex;align-items:center;justify-content:space-between;margin-bottom:28px}.brand{display:flex;gap:13px;align-items:center}.mark{width:42px;height:42px;border:1px solid #3c5873;border-radius:13px;display:grid;place-items:center;background:#0d2236;color:var(--mint);font-weight:900}.brand h1{font-size:20px;margin:0}.brand p{margin:2px 0 0;color:var(--muted);font-size:12px}.health{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:13px}.dot{width:8px;height:8px;border-radius:50%;background:var(--red);box-shadow:0 0 12px currentColor}.dot.ok{background:var(--mint)}
    .grid{display:grid;grid-template-columns:310px 1fr;gap:20px}.panel{background:#0d1928e8;border:1px solid var(--line);border-radius:18px;box-shadow:0 18px 60px #0005}.commission{padding:22px;align-self:start}.eyebrow{margin:0 0 7px;color:var(--mint);font-size:11px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.panel h2{font-size:18px;margin:0 0 7px}.hint{color:var(--muted);font-size:13px;margin:0}.qr{width:100%;aspect-ratio:1;margin:20px 0 16px;padding:12px;border-radius:14px;background:#fff}.code{padding:11px;border-radius:10px;background:#07111f;border:1px solid var(--line);text-align:center;font:700 18px ui-monospace,monospace;letter-spacing:.08em}.badge{display:inline-flex;padding:6px 10px;border-radius:999px;background:#17372f;color:var(--mint);font-size:12px;font-weight:700}.commission-actions{display:grid;gap:12px}.reconnect{width:100%;border:1px solid #744251;background:#351c27;color:#ffdce2;border-radius:10px;padding:10px 12px;cursor:pointer;font-weight:700}.reconnect:disabled{opacity:.5;cursor:wait}.warning{margin:0;color:#d49aa6;font-size:11px}.hidden{display:none!important}
    .devices{padding:22px}.devices-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:17px}.devices-head h2{margin:0}.refresh{border:1px solid var(--line);background:#122337;color:var(--text);border-radius:9px;padding:8px 11px;cursor:pointer}.device-list{display:grid;gap:14px}.empty{border:1px dashed #30465d;border-radius:14px;padding:48px 20px;text-align:center;color:var(--muted)}.device{border:1px solid var(--line);border-radius:14px;padding:16px;background:#0b1725}.device-top{display:flex;justify-content:space-between;gap:15px;margin-bottom:14px}.device-name{font-size:16px;font-weight:750}.meta{color:var(--muted);font-size:12px;margin-top:3px}.online{color:var(--mint)}.offline{color:var(--red)}.outlets{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.outlet{border:1px solid var(--line);border-radius:12px;padding:12px;background:#0e1c2c;min-width:0}.outlet-row{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.switch{position:relative;width:38px;height:22px;border:0;border-radius:99px;background:#314358;cursor:pointer;transition:.2s}.switch:after{content:"";position:absolute;left:3px;top:3px;width:16px;height:16px;border-radius:50%;background:#d9e5ef;transition:.2s}.switch.on{background:var(--mint)}.switch.on:after{transform:translateX(16px);background:#06231a}.switch:disabled{opacity:.4;cursor:not-allowed}.reading{font-size:18px;font-weight:750}.reading small{font-size:11px;color:var(--muted);font-weight:500}.subreading{color:var(--muted);font-size:11px;margin-top:2px}.toast{position:fixed;right:20px;bottom:20px;max-width:360px;background:#351622;border:1px solid #743345;color:#ffdce2;padding:12px 16px;border-radius:11px;box-shadow:0 10px 40px #0008}
    .device-actions{display:flex;flex-direction:column;align-items:flex-end;gap:8px;flex-shrink:0}.delete-device{border:1px solid #744251;background:#351c27;color:#ffdce2;border-radius:8px;padding:5px 10px;cursor:pointer}.delete-device:disabled{opacity:.5;cursor:wait}
    @media(max-width:820px){.grid{grid-template-columns:1fr}.commission{display:grid;grid-template-columns:150px 1fr;gap:16px}.commission .qr{grid-row:1/5;margin:0}.outlets{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){main{width:min(100% - 20px,1160px);padding-top:20px}.commission{display:block}.commission .qr{margin:18px 0}.outlets{grid-template-columns:1fr 1fr}.reading{font-size:16px}}
  </style>
</head>
<body><main>
  <header><div class="brand"><div><h1>MTTL-W01 Matter Bridge</h1></div></div><div class="health"><i id="health-dot" class="dot"></i><span id="health">연결 확인 중</span></div></header>
  <div class="grid">
    <section class="panel commission">
      <div><p class="eyebrow">Matter setup</p><h2 id="setup-title">Matter 연결</h2><p id="setup-hint" class="hint">Matter 앱에서 QR 코드를 스캔하세요.</p></div>
      <img id="qr" class="qr" src="/commissioning/qr.svg" alt="Matter 페어링 QR 코드">
      <div id="manual-wrap"><p class="hint" style="margin-bottom:6px">수동 페어링 코드</p><div id="manual" class="code">—</div></div>
      <div id="commissioned-actions" class="commission-actions hidden"><div class="badge">Matter 연결 완료</div><button id="reconnect-matter" class="reconnect" type="button">Matter 재연결</button></div>
    </section>
    <section class="panel devices">
      <div class="devices-head"><div><p class="eyebrow">Devices</p><h2>연결된 멀티탭 <span id="count">0</span></h2></div><button class="refresh" id="refresh">새로고침</button></div>
      <div id="device-list" class="device-list"><div class="empty">연결된 장치가 없습니다.</div></div>
    </section>
  </div>
</main><div id="toast" class="toast hidden"></div>
<script>
  const list=document.querySelector('#device-list'), count=document.querySelector('#count');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const number=(v,d=1)=>v==null?'—':Number(v).toFixed(d);
  function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3500)}
  function renderCommissioning(info){const qr=document.querySelector('#qr'),manual=document.querySelector('#manual-wrap'),actions=document.querySelector('#commissioned-actions');document.querySelector('#manual').textContent=info.manualPairingCode;if(info.commissioned){qr.classList.add('hidden');manual.classList.add('hidden');actions.classList.remove('hidden');document.querySelector('#setup-title').textContent='연결됨';document.querySelector('#setup-hint').textContent='Matter 패브릭에 등록된 브리지입니다.'}else{qr.classList.remove('hidden');manual.classList.remove('hidden');actions.classList.add('hidden');document.querySelector('#setup-title').textContent='Matter 연결';document.querySelector('#setup-hint').textContent='Matter 앱에서 QR 코드를 스캔하세요.'}}
  async function reconnectMatter(){if(!confirm('Matter 연결을 초기화하면 연결된 모든 플랫폼에서 다시 페어링해야 합니다. 계속할까요?'))return;const button=document.querySelector('#reconnect-matter');button.disabled=true;button.textContent='초기화 중…';try{const r=await fetch('/matter/reconnect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirm:true})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Matter 재연결 준비 실패');document.querySelector('#qr').src='/commissioning/qr.svg?t='+Date.now();renderCommissioning(data.commissioning);toast('Matter 연결이 초기화되었습니다. QR 코드를 다시 스캔하세요.')}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent='Matter 재연결'}}
  async function control(id,index,on,button){button.disabled=true;try{const r=await fetch('/devices/'+encodeURIComponent(id)+'/outlets/'+index+'/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({on})});const data=await r.json();if(!r.ok)throw new Error(data.error||'제어 실패');await refresh()}catch(e){toast(e.message)}finally{button.disabled=false}}
  const deleting=new Set();
  async function removeDevice(id,name){if(deleting.has(id)||!confirm(name+' 기기를 삭제할까요? Matter 브리지와 저장된 기기 목록에서 제거됩니다. 기기가 다시 연결되면 자동으로 등록됩니다.'))return;deleting.add(id);list.querySelectorAll('.delete-device').forEach(b=>{if(b.dataset.id===id){b.disabled=true;b.textContent='삭제 중…'}});try{const r=await fetch('/devices/'+encodeURIComponent(id),{method:'DELETE'});const data=await r.json();if(!r.ok)throw new Error(data.error||'기기 삭제 실패');await refresh();toast('기기가 삭제되었습니다.')}catch(e){toast(e.message)}finally{deleting.delete(id);list.querySelectorAll('.delete-device').forEach(b=>{if(b.dataset.id===id){b.disabled=false;b.textContent='삭제'}})}}
  function render(devices){count.textContent=devices.length;if(!devices.length){list.innerHTML='<div class="empty">연결된 장치가 없습니다.</div>';return}list.innerHTML=devices.map(d=>'<article class="device"><div class="device-top"><div><div class="device-name">'+esc(d.name)+'</div><div class="meta">'+esc(d.id)+' · FW '+esc(d.firmwareVersion||'—')+'</div></div><div class="device-actions"><div class="'+(d.reachable?'online':'offline')+'">● '+(d.reachable?'온라인':'오프라인')+'</div>'+(!d.reachable?'<button type="button" class="delete-device" data-id="'+esc(d.id)+'" data-name="'+esc(d.name||d.id)+'" '+(deleting.has(d.id)?'disabled':'')+'>'+(deleting.has(d.id)?'삭제 중…':'삭제')+'</button>':'')+'</div></div><div class="outlets">'+d.outlets.map(o=>'<div class="outlet"><div class="outlet-row"><strong>'+o.index+'구</strong><button aria-label="'+o.index+'구 전원" class="switch '+(o.on?'on':'')+'" data-id="'+esc(d.id)+'" data-index="'+o.index+'" data-next="'+(!o.on)+'" '+(!d.reachable?'disabled':'')+'></button></div><div class="reading">'+number(o.powerW)+' <small>W</small></div><div class="subreading">'+number(o.energyWh,2)+' Wh · '+number(o.temperatureC,0)+' °C</div></div>').join('')+'</div></article>').join('');list.querySelectorAll('.switch').forEach(b=>b.onclick=()=>control(b.dataset.id,Number(b.dataset.index),b.dataset.next==='true',b));list.querySelectorAll('.delete-device').forEach(b=>b.onclick=()=>removeDevice(b.dataset.id,b.dataset.name))}
  async function refresh(){try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw new Error('상태 조회 실패');const data=await r.json();document.querySelector('#health-dot').classList.add('ok');document.querySelector('#health').textContent='연결됨';renderCommissioning(data.commissioning);render(data.devices)}catch(e){document.querySelector('#health-dot').classList.remove('ok');document.querySelector('#health').textContent='서버 연결 끊김';toast(e.message)}}
  document.querySelector('#refresh').onclick=refresh;document.querySelector('#reconnect-matter').onclick=reconnectMatter;refresh();setInterval(()=>{if(!document.hidden)refresh()},3000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
</script></body></html>`;
